### ISSUE TITLE
No call to outside service via CEP consumer

### ISSUE THREAD

**Issue by aoikon68** [Bitergia/fiware-chanchan-docker#15] opened 2016-08-17 16:56 UTC
I have installed a Proton CEP docker container and my project receives events smoothly both from POSTMAN and outside source. Unfortunately, the consumer I use as a REST client in order to send derived events to outside service does not work at all.
In log I see events coming properly, system responds with the message "to consumer..." following the project's rules, BUT nothing arrives to outside service.
I have tried manualy to post data to outside service from within the container via wget and works perfectly.
I have really reached a dead end and don't know what else to do. I have checked CEP configuration (Proton.properties etc) thoroughly and multiple times but with no luck.
Any help will be very much appreciated.

**Comment by aoikon68** [comment] 2016-08-18 15:58
I finally found a solution and that is to assign different port numbers inside Proton.properties file of my project from those in the same file of the ProtonOnWebServer and problem is solved.

**Comment by albertinisg** [comment] 2016-08-19 11:30
Thanks for the feedback @aoikon68 and sorry for the late reply. 

Currently the CEP image from this repository is no longer maintained, as we are migrating to the official ones. Here you can find the official repositories of CEP:
- Github: https://github.com/ishkin/Proton
- Official Docker image: https://hub.docker.com/r/fiware/proactivetechnologyonline

As the problem is already solved, I'm closing this.

**Closed as completed by albertinisg** 2016-08-19 11:30 UTC
